#ifndef CHEAPBIN_RE_DATA_H
#define CHEAPBIN_RE_DATA_H

/*
 * re_data.h — Reverse-engineering culture database for cheapbin
 *
 * 1000+ quotes, opcodes, binary strings, and ASCII art fragments
 * curated for the reversing / chiptune / hacker community.
 */

/* ── RE / Hacker / Chiptune Quotes ─────────────────────────────────── */

static const char *RE_QUOTES[] = {
    /* Classic RE wisdom */
    "The code is the documentation.",
    "All software can be understood; some is just harder.",
    "Every binary tells a story.",
    "mov eax, coffee ; essential instruction",
    "Read the disassembly, Luke.",
    "When in doubt, strace it out.",
    "In IDA we trust.",
    "Ghidra: because RE should be free.",
    "There are 10 types of people: those who read hex and F the rest.",
    "Your binary is showing.",
    "NOP NOP NOP... slide into my DMs.",
    "Patching is an art form.",
    "Strings: the reverser's best friend.",
    "If it compiles, ship it. If it runs, reverse it.",
    "OllyDbg remembers.",
    "Breakpoints are just suggestions.",
    "int 3 is my safe word.",
    "CALL me maybe.",
    "There is no cloud, just someone else's mov eax.",
    "sudo make me a sandwich ; then reverse it",
    "Obfuscation is just job security for reverse engineers.",
    "Anti-debug? More like anti-fun.",
    "I came, I saw, I decompiled.",
    "Life is short. Reverse everything.",
    "Keep calm and disassemble.",
    "One does not simply walk into ring 0.",
    "My other car is a debugger.",
    "0xDEADBEEF walks into a bar...",
    "Friend: 'What do you do?' Me: 'I break software for a living.'",
    "I void warranties.",
    "Roses are #FF0000, violets are #0000FF, all my base are belong to you.",
    "The best debugger is a fresh pair of eyes.",
    "Segfault is just the binary saying hello.",
    "Real programmers use butterflies.",
    "Speak softly and carry a big disassembler.",
    "May your offsets always be correct.",
    "Don't talk to me until I've had my 0xC0FFEE.",
    "ROP chains: because who needs source code?",
    "ret2libc: the lazy reverser's exploit.",
    "I don't always reverse, but when I do, I prefer hex.",
    /* Hacker culture */
    "Hack the planet!",
    "Information wants to be free.",
    "The quieter you become, the more you can hear.",
    "In a world of locked doors, the person with the key is king.",
    "There's no place like 127.0.0.1.",
    "sudo rm -rf doubts",
    "chmod 777 your_mind",
    "It's not a bug, it's a feature.",
    "Works on my machine.",
    "Have you tried turning it off and on again?",
    "Hello, friend.",
    "Follow the white rabbit.",
    "The Matrix has you.",
    "I know kung fu. Show me.",
    "Free your mind.",
    "Wake up, Neo...",
    "Knock knock, Neo.",
    "There is no spoon.",
    "I can only show you the door. You have to walk through it.",
    "What is real? How do you define real?",
    "This is your last chance. Red pill or blue pill?",
    "Whoa.",
    "Guns. Lots of guns.",
    "Why, oh why, didn't I take the BLUE pill?",
    "Ignorance is bliss.",
    "The answer is out there. It's looking for you.",
    "Do not try to bend the binary. Instead, try to realize the truth.",
    "The binary is everywhere. It's all around us.",
    /* Binary / Hex culture */
    "There are only two hard things: cache invalidation and naming things.",
    "0xCAFEBABE just entered the chat.",
    "0xDEADC0DE: where bugs go to die.",
    "Little endian or big endian? Yes.",
    "ASLR: Hide and seek for grown-ups.",
    "A wild NOP sled appears!",
    "Buffer overflow: write what you want, where you want.",
    "Off by one? Off by fun!",
    "Heap spray and pray.",
    "Use after free? Use after me.",
    "Double free or nothing.",
    "Format strings: printf's revenge.",
    "Integer overflow: when math attacks.",
    "Stack canary: the bird in the coal mine.",
    "RELRO: Read-only after relocation.",
    "PIE: Position Independent but still findable.",
    "NX bit: No execute, no problem... unless you ROP.",
    "SEH: Structured Exception Handling or Sneaky Exploit Helper?",
    "VTable hijacking: OOP's dirty little secret.",
    "Race condition: may the fastest thread win.",
    "TOCTOU: time of check, time of getting owned.",
    /* Chiptune / Music */
    "8 bits of pure joy.",
    "All your bass are belong to us.",
    "Chiptune is not dead, it's just 8-bit.",
    "Every byte is a note waiting to be heard.",
    "Music is just math you can dance to.",
    "Waveforms: the poetry of electrons.",
    "Square waves never die.",
    "Triangle waves: the warm hug of 8-bit.",
    "Sawtooth: the angry wave.",
    "Noise channel: controlled chaos.",
    "LFO: Low Frequency Oscillation, High Frequency Fun.",
    "ADSR: Attack, Decay, Sustain, Rock.",
    "Arpeggio: because one note is never enough.",
    "Duty cycle: not just a military thing.",
    "Pulse width modulation: the secret sauce.",
    "echo 'hello world' | aplay",
    "The SID chip was ahead of its time.",
    "MOS 6581: the voice of a generation.",
    "YM2612: Sega's secret weapon.",
    "Ricoh 2A03: NES's musical heart.",
    "Game Boy had 4 channels and infinite charm.",
    "Amiga: 4 channels of MOD bliss.",
    "Tracker music: where geeks become composers.",
    "MOD, XM, IT, S3M: the formats that defined a scene.",
    "Demoscene: art meets assembly.",
    "Sizecoding: less is more.",
    "64 bytes of music. Challenge accepted.",
    "The best music fits in a floppy disk.",
    "Keygen music > radio music.",
    "The cracktro was better than the game.",
    "Intro music: 4KB of pure nostalgia.",
    "Fairlight, Razor1911, PARADOX — legends.",
    /* Programming / CS humor */
    "A SQL query walks into a bar, sees two tables, and asks: 'Can I join you?'",
    "// TODO: make this less terrible",
    "// FIXME: this is a hack",
    "// HACK: I know what I'm doing... maybe",
    "/* this code is self-documenting */",
    "// Here be dragons",
    "// Abandon all hope, ye who enter here",
    "// I'm sorry",
    "// Magic. Do not touch.",
    "// If this code works, it was written by me. If not, I don't know who wrote it.",
    "// Drunk. Fix later.",
    "// Dear future me: I'm sorry.",
    "// This was harder than it looks.",
    "// No one will ever read this.",
    "// I am not responsible for this code.",
    "There's no place like ~",
    "mkdir -p ~/happiness",
    "while true; do coffee; done",
    "git commit -m 'fixed the thing'",
    "git push --force # YOLO",
    "git blame: the code archaeology tool.",
    "Merge conflict: developer vs developer.",
    "99 little bugs in the code, 99 little bugs...",
    "Take one down, patch it around, 127 little bugs in the code.",
    "It works on my machine. Ship my machine.",
    "Premature optimization is the root of all evil.",
    "Always code as if the person maintaining your code is a violent psychopath.",
    "The first rule of debugging: it's always your fault.",
    "printf debugging: the oldest tool in the book.",
    "gdb: the debugger that debugs your debugging.",
    "valgrind: memory's guardian angel.",
    "Undefined behavior: the compiler's revenge.",
    "Compiler warnings are love letters from your tools.",
    "C: the language where you ARE the garbage collector.",
    "malloc/free: the dance of memory.",
    "Pointers: because life was too easy.",
    "Segmentation fault (core dumped) — the haiku of C.",
    "In C we trust, in Rust we verify.",
    "Assembly: where men are men and pointers are pointers.",
    "x86: the architecture that refuses to die.",
    "ARM: because x86 was too predictable.",
    "RISC-V: the open source dream.",
    "MIPS: Microprocessor without Interesting Pipeline Stalls.",
    /* Security / CTF */
    "CTF: Capture The Flag, not The Frustration.",
    "pwned: a state of mind.",
    "Shell acquired. Root pending.",
    "Privilege escalation: the social climbing of binaries.",
    "Sandbox escape: the binary's prison break.",
    "Fuzzing: throw garbage at it until it breaks.",
    "AFL: American Fuzzy Lop, not the rabbit.",
    "AddressSanitizer: the memory police.",
    "ASAN, MSAN, UBSAN: the sanitizer squad.",
    "Reverse shell: calling home from behind enemy lines.",
    "Payload delivered. Awaiting callback.",
    "Zero-day: the holy grail.",
    "CVE: Certified Vulnerability Experience.",
    "Bug bounty: getting paid to break things.",
    "Responsible disclosure: hacking with manners.",
    "Red team: offense wins championships.",
    "Blue team: defense never sleeps.",
    "Purple team: why not both?",
    "Pentest report: 'Everything is broken. Here's how.'",
    "Social engineering: hacking the wetware.",
    "The weakest link is between the keyboard and chair.",
    "Two-factor: because passwords are not enough.",
    "Encryption: math that keeps secrets.",
    "XOR: the reverser's best friend.",
    "ROT13: encryption for kindergartners.",
    "Base64: not encryption, just encoding.",
    "SHA-256: trust but verify.",
    "RSA: Really Slow Algorithm.",
    "AES: Actually Effective Security.",
    "TLS: Trust, but Layer your Security.",
    /* Binary analysis */
    "readelf: reading between the lines.",
    "objdump: the binary's diary.",
    "nm: naming names.",
    "ldd: who are your dependencies?",
    "ltrace: library calls exposed.",
    "strace: the system call whisperer.",
    "file: what are you, really?",
    "hexdump: seeing the matrix.",
    "xxd: hex's best friend.",
    "binwalk: the firmware archaeologist.",
    "radare2: r2 or r2pipe? Both.",
    "Binary Ninja: the new kid on the block.",
    "Hopper: macOS reversing's go-to.",
    "x64dbg: OllyDbg's spiritual successor.",
    "Cutter: radare2 with a GUI.",
    "PE, ELF, Mach-O: the binary trinity.",
    "ELF: Executable and Linkable (and Fascinating).",
    "Mach-O: Apple's binary baby.",
    "PE: Portable Executable, universally confusing.",
    ".text: where the action is.",
    ".data: the binary's filing cabinet.",
    ".bss: the section of unfulfilled promises.",
    ".rodata: read-only, write-never.",
    ".plt: Procedure Linkage Table, or Please Look There.",
    ".got: Global Offset Table, or Getting Owned Today.",
    "Import Address Table: the binary's phone book.",
    "Symbol table: the binary's yearbook.",
    "DWARF: debugging information, not the fantasy creature.",
    "PDB: Program Database, or Pretty Darn Big.",
    /* OS internals */
    "Kernel: the OS's inner sanctum.",
    "Ring 0: where the magic happens.",
    "Syscall: politely asking the kernel.",
    "Context switch: the kernel's multitasking.",
    "Page fault: the memory's 'address not found'.",
    "Virtual memory: the great pretender.",
    "TLB: Translation Lookaside Buffer, or The Lookup Buddy.",
    "MMU: Memory Management Unit, the traffic cop.",
    "Interrupt: the CPU's 'excuse me'.",
    "DMA: Direct Memory Access, no CPU required.",
    "IOCTL: I/O Control, the Swiss Army knife.",
    "procfs: /proc/self/enlightenment",
    "sysfs: the kernel's show-and-tell.",
    "dmesg: the kernel's diary.",
    "eBPF: the kernel's safe playground.",
    "kprobes: poking the kernel, gently.",
    "ftrace: tracing the kernel's footsteps.",
    /* More RE culture */
    "What hath God wrought? — first telegraph, first binary.",
    "To reverse is human, to decompile divine.",
    "Behind every great program is a great disassembly.",
    "The map is not the territory; the binary is not the source.",
    "If you can't explain it simply, you haven't reversed it enough.",
    "Understanding a binary is like learning a new language.",
    "Every vulnerability was once just a feature.",
    "The best exploit is the one you don't need.",
    "Complexity is the enemy of security.",
    "Simple systems are harder to break.",
    "Trust nothing, verify everything.",
    "Defense in depth: because one layer is never enough.",
    "Assume breach.",
    "The attacker only needs to be right once.",
    "The defender needs to be right every time.",
    "Know your enemy, know yourself.",
    "Security is a process, not a product.",
    "The only secure computer is one that's turned off.",
    "Even then, I wouldn't bet on it.",
    /* Nerdy one-liners */
    "I'd tell you a UDP joke, but you might not get it.",
    "A TCP packet walks into a bar and says 'I'd like a beer.' The bartender replies 'You'd like a beer?' 'Yes, a beer.'",
    "There are two ways to write error-free programs; only the third one works.",
    "Programming is 10% writing code and 90% understanding why it doesn't work.",
    "Debugging is twice as hard as writing code. So if you write code as cleverly as possible, you are by definition not smart enough to debug it.",
    "The best thing about a boolean is even if you're wrong, you're only off by a bit.",
    "Why do programmers prefer dark mode? Because light attracts bugs.",
    "A foo walks into a bar, takes a look around and says 'Hello, World!'",
    "In theory, theory and practice are the same. In practice, they're not.",
    "Unix is user-friendly. It's just picky about who its friends are.",
    "Linux: because rebooting is for adding new hardware.",
    "vi has two modes: one that beeps and one that corrupts your file.",
    "Emacs: a great operating system, lacking only a decent editor.",
    "Eight megabytes and constantly swapping.",
    "tar -xzf: because remembering flags builds character.",
    "man: the command that teaches you to RTFM.",
    "RTFM: the answer to 90% of all questions.",
    "Stack Overflow: where we all secretly look for answers.",
    "Copy-paste from SO: the real 10x developer move.",
    "GitHub Copilot: pair programming with a ghost.",
    "AI can write code, but can it reverse it?",
    "Machine learning: statistics on steroids.",
    "Neural networks: brains, but worse.",
    "Deep learning: deeper into confusion.",
    "The Cloud: someone else's computer.",
    "Serverless: still has servers, just not your problem.",
    "Docker: it works in my container.",
    "Kubernetes: Docker's overachieving sibling.",
    "YAML: Yet Another Markup Language that will ruin your day.",
    "JSON: JavaScript's gift to the world.",
    "XML: because JSON wasn't verbose enough.",
    "Regex: now you have two problems.",
    "Perl: write once, read never.",
    "Python: because life's too short for semicolons.",
    "Rust: the borrow checker says no.",
    "Go: where generics finally arrived.",
    "JavaScript: the language of the web, for better or worse.",
    "TypeScript: JavaScript with a safety net.",
    "Haskell: where monads make everything clear. Or do they?",
    "Lisp: parentheses all the way down.",
    "Forth: stack-based and proud of it.",
    "COBOL: still running the world's banks.",
    "Fortran: the original number cruncher.",
    "Assembly: the lingua franca of hardware.",
    /* Philosophical / Deep */
    "What does your binary dream about?",
    "If a binary crashes in the forest, does it make a sound?",
    "The meaning of life: 0x2A.",
    "42 in hex: the answer to everything.",
    "pi = 3.14159... but in binary it's still irrational.",
    "e = 2.71828... Euler's number, nature's constant.",
    "Fibonacci: nature's algorithm.",
    "The halting problem: some questions have no answer.",
    "Gödel's theorem: even math has its limits.",
    "Turing completeness: your language can do anything... eventually.",
    "Church-Turing thesis: all computers are equal (given enough tape).",
    "P vs NP: the million-dollar question.",
    "NP-complete: hard in theory, harder in practice.",
    "Big O: how we measure code ego.",
    "O(1): the holy grail.",
    "O(n): perfectly balanced, as all things should be.",
    "O(n²): nested loops, nested problems.",
    "O(n!): factorial, factually terrible.",
    "O(log n): the binary search sweet spot.",
    "Divide and conquer: the algorithm's war strategy.",
    "Dynamic programming: remembering so you don't repeat.",
    "Recursion: see 'Recursion'.",
    "To understand recursion, first understand recursion.",
    "Base case: the only thing standing between you and a stack overflow.",
    /* More hacker / RE */
    "Patching binaries by moonlight.",
    "My disassembler brings all the nerds to the yard.",
    "Come for the reversing, stay for the chiptunes.",
    "What does your /bin/sh sound like?",
    "Every ELF has a song inside.",
    "Mach-O Mach-O man, I want to be a Mach-O man.",
    "PE header? I hardly know her!",
    "Section headers: the binary's table of contents.",
    "Dynamic linking: making friends at runtime.",
    "Static linking: the lone wolf approach.",
    "Strip -s: witness protection for symbols.",
    "UPX: the binary diet plan.",
    "Packers: gift wrapping for malware.",
    "Crypters: because packers weren't sneaky enough.",
    "VMProtect: making reversers cry since forever.",
    "Themida: the binary's bodyguard.",
    "Control flow flattening: the obfuscator's favorite.",
    "Opaque predicates: always true, never obvious.",
    "Dead code insertion: the filler episode of binaries.",
    "Code virtualization: an interpreter within an interpreter.",
    "Self-modifying code: the binary that rewrites itself.",
    "Metamorphic code: the shapeshifter.",
    "Polymorphic code: same virus, different face.",
    "Anti-disassembly: linear sweep's worst nightmare.",
    "Junk bytes: the reverser's red herring.",
    "Call stack unwinding: the detective's trail.",
    "Return-oriented programming: Frankenstein's exploit.",
    "Jump-oriented programming: ROP's cousin.",
    "Sigreturn-oriented programming: even the kernel helps.",
    "Blind ROP: exploiting without seeing.",
    "ASLR bypass: finding needles in randomized haystacks.",
    "Stack pivot: changing the rules mid-game.",
    "Heap feng shui: arranging memory just right.",
    "Type confusion: when the compiler lies.",
    "Use-after-free: the zombie pointer.",
    "Dangling pointer: the ghost of allocations past.",
    "Wild pointer: the untamed beast.",
    "NULL dereference: the simplest crash.",
    "The billion-dollar mistake: NULL itself.",
    "Memory corruption: the root of all exploits.",
    "Bounds checking: the thing C forgot.",
    "Canary: tweet tweet, stack smashed.",
    "Shadow stack: the backup plan.",
    "CFI: Control Flow Integrity, the bouncer at the door.",
    "CET: Control-flow Enforcement Technology.",
    "PAC: Pointer Authentication Codes, ARM's security flex.",
    "MTE: Memory Tagging Extension, coloring memory.",
    /* Pop culture references */
    "I'm in.",
    "Access granted.",
    "Mainframe accessed.",
    "Downloading... 99%...",
    "Hack complete.",
    "System compromised.",
    "Target acquired.",
    "Decrypting...",
    "Firewall bypassed.",
    "Trace route complete.",
    "Signal acquired.",
    "Handshake established.",
    "Tunnel open.",
    "Connection secure.",
    "Root access obtained.",
    "Elevating privileges...",
    "Injecting payload...",
    "Shellcode deployed.",
    "Backdoor installed.",
    "Persistence established.",
    "Covering tracks...",
    "Ghost in the machine.",
    "Ghost in the shell.",
    "The net is vast and infinite.",
    "I am the law. — Judge Dredd, also EULA",
    "I'll be back. — every recursive function",
    "Hasta la vista, baby. — garbage collector",
    "Do. Or do not. There is no try-catch. — Yoda",
    "Use the source, Luke. — open source Jedi",
    "I see dead processes. — kill -9",
    "You shall not pass! — firewall",
    "One ring(0) to rule them all.",
    "Elementary, my dear Watson. — Sherlock on stack traces",
    "The truth is out there. — Mulder on crash dumps",
    "To infinity and beyond! — while(1)",
    "Houston, we have a segfault.",
    "That's one small step for code, one giant leap for codekind.",
    "E.T. phone 127.0.0.1.",
    "Ph'nglui mglw'nafh Cthulhu R'lyeh wgah'nagl fhtagn. — obfuscated code",
    "Winter is coming. — legacy code migration",
    "You know nothing, Jon Snow. — junior dev reading kernel source",
    "A Lannister always pays his technical debt.",
    "Valar Morghulis — All processes must die.",
    "Hold the door! Hold the mutex!",
    "Not all who wander are lost. Some are just doing DFS.",
    "It's dangerous to go alone! Take this debugger.",
    "The cake is a lie. So is thread safety.",
    /* More technical humor */
    "We've been trying to reach you about your binary's extended warranty.",
    "Your call is important to us. Please hold while we NOP.",
    "This binary has been rated R for Reversing.",
    "Viewer discretion advised: contains strong hex language.",
    "No binaries were harmed in the making of this chiptune.",
    "Side effects may include: hex vision, stack dreams, binary earworms.",
    "Warning: listening to /bin/ls may cause spontaneous debugging.",
    "Caution: this program may induce nostalgia for 8-bit computing.",
    "For best results, listen with headphones and a hex editor open.",
    "This chiptune was generated by pure binary analysis. No AI involved.*",
    "* Narrator: there was definitely math involved.",
    "Achievement unlocked: listened to a binary.",
    "New high score: 0xFFFFFFFF",
    "Player 1 ready. Press space to pause.",
    "Insert coin to continue... just kidding, it's open source.",
    "Loading... ████████████████ 100% — actually instant.",
    "Defragmenting your music... done.",
    "Compiling your binary into beats...",
    "Linking your library into lyrics...",
    "Resolving your symbols into sound...",
    "Translating opcodes to octaves...",
    "Converting jumps to jams...",
    "Parsing procedures into percussion...",
    "Decompiling data into drums...",
    "Decoding your binary's hidden rhythm...",
    "Every executable has a soundtrack. You just need cheapbin.",
    "cheapbin: turning /usr/bin into /usr/beats.",
    "cheapbin: where reverse engineering meets raving.",
    "cheapbin: the sound of software.",
    "cheapbin: hear what your code really sounds like.",
    "cheapbin: binary audio forensics.",
    "cheapbin: because strings(1) was too quiet.",
    "This binary slaps.",
    "Straight fire from the .text section.",
    "The .data section has bars.",
    "Dropping beats from the GOT.",
    "PLT: Procedurally Linked Tracks.",
    "ELF on the shelf, making chiptunes.",
    "Mach-O-matic music machine.",
    "PE-rfect pitch from your binaries.",
    /* Famous computing quotes adapted */
    "The best way to predict the future is to disassemble it.",
    "Move fast and break binaries.",
    "Talk is cheap. Show me the disassembly.",
    "First, solve the problem. Then, reverse the solution.",
    "Simplicity is the soul of efficiency. — Austin Freeman, also good code",
    "Any sufficiently advanced technology is indistinguishable from magic.",
    "Any sufficiently advanced bug is indistinguishable from a feature.",
    "Any sufficiently analyzed binary is indistinguishable from source code.",
    "Programs must be written for people to read, and only incidentally for machines to execute.",
    "Binaries must be reversed for people to understand, and only incidentally for machines to patch.",
    "The computer was born to solve problems that did not exist before.",
    "Hardware eventually fails. Software eventually works.",
    "Software is like entropy: it always increases.",
    "Good artists copy, great artists reverse engineer.",
    "Be curious. Read code. Break things. Fix them. Repeat.",
    "The only way to learn RE is to RE.",
    "Stay hungry, stay foolish, stay reversing.",
    "Think different. Think in hex.",
    "Innovation distinguishes between a reverser and a script kiddie.",
    "Your time is limited. Don't waste it living without a debugger.",
    /* Short punchy */
    "PUSH it real good.",
    "POP goes the register.",
    "JMP around.",
    "Don't CALL us, we'll CALL you.",
    "RET to sender.",
    "CMP and contrast.",
    "TEST your limits.",
    "AND that's the truth.",
    "OR is it?",
    "XOR nothing.",
    "NOT today.",
    "SHL happens.",
    "SHR enough.",
    "ROL with it.",
    "LEA the way.",
    "MOV on.",
    "SUB zero.",
    "ADD it up.",
    "MUL tiplied efforts.",
    "DIV erse opinions.",
    "INC redible.",
    "DEC ision time.",
    "NOP. Just NOP.",
    "INT eresting.",
    "LOOP de loop.",
    "REP eat after me.",
    "XCHG your perspective.",
    "ENTER the void.",
    "LEAVE no trace.",
    "HLT. Hammertime.",
    "CPUID yourself.",
    "RDTSC: measuring time, one tick at a time.",
    "SYSCALL: asking nicely.",
    "SYSENTER: asking less nicely.",
    "IRET: interrupt return, or 'I'm done here'.",
    "STI: start the interrupts.",
    "CLI: clear the interrupts, clear your mind.",
    "CLD: clear direction, find your path.",
    /* Programming mantras */
    "KISS: Keep It Simple, Stupid.",
    "DRY: Don't Repeat Yourself.",
    "YAGNI: You Aren't Gonna Need It.",
    "SOLID: the OOP commandments.",
    "RTFM: Read The Fine Manual.",
    "PEBKAC: Problem Exists Between Keyboard And Chair.",
    "LGTM: Looks Good To Me (didn't actually review).",
    "WONTFIX: the issue's graveyard.",
    "NOTABUG: the developer's shield.",
    "TL;DR: the modern summary.",
    /* Hardware */
    "6502: the chip that built an empire.",
    "Z80: Zilog's masterpiece.",
    "8086: where it all began.",
    "68000: Motorola's finest hour.",
    "ARM: the chip that runs the world.",
    "RISC vs CISC: the eternal debate.",
    "Pipeline stall: the CPU's traffic jam.",
    "Branch prediction: the CPU's crystal ball.",
    "Cache miss: the CPU's worst nightmare.",
    "Register file: the CPU's scratch pad.",
    "ALU: Arithmetic Logic Unit, the brain's brain.",
    "FPU: Floating Point Unit, for when integers aren't enough.",
    "SIMD: Single Instruction, Multiple Data, maximum throughput.",
    "SSE, AVX: Intel's parallel playground.",
    "NEON: ARM's SIMD answer.",
    "Microcode: the instruction's instruction.",
    "Spectre: when speculation goes wrong.",
    "Meltdown: when isolation melts away.",
    "Rowhammer: when physics attacks security.",
    "Side channels: information leaks everywhere.",
    /* Misc geek */
    "640K ought to be enough for anybody... right?",
    "Hello, World! — the first program everyone writes.",
    "FizzBuzz: the interview's rite of passage.",
    "Leetcode: the modern day hazing.",
    "Whiteboard coding: writing without backspace.",
    "Technical debt: the mortgage of software.",
    "Refactoring: cleaning up someone else's mess.",
    "Code review: finding bugs in code that 'works'.",
    "Ship it! (and fix it in production)",
    "Feature flag: Schrödinger's feature.",
    "Canary deployment: the cautious rollout.",
    "Blue-green deployment: the colorful rollout.",
    "Chaos engineering: breaking things on purpose.",
    "Observability: knowing what you don't know.",
    "SRE: Software Reliability Engineering, or Sleeping Really Early.",
    "On-call: the developer's night shift.",
    "PagerDuty: the sound of dread at 3 AM.",
    "Postmortem: the autopsy of an outage.",
    "Blameless culture: it was the code's fault.",
    "Incident response: controlled panic.",
    "Runbook: the recipe for fixing things.",
    "Dashboard: pretty graphs that nobody checks until something breaks.",
    "Alert fatigue: crying wolf, digitally.",
    "Log level DEBUG: when you really want to know.",
    "Log level FATAL: when it's too late.",
    "stdout vs stderr: the great debate.",
    "Piping: Unix's greatest invention.",
    "Everything is a file. — Unix philosophy",
    "Do one thing and do it well. — Unix philosophy",
    "Small, sharp tools. — Unix philosophy",
    "Worse is better. — The New Jersey approach",
    "Less is more. — also applies to code and chiptunes",
    /* Final batch */
    "Never trust user input. Or binary headers.",
    "Sanitize everything. Even your hex dumps.",
    "The entropy is high with this one.",
    "May your reversing sessions be fruitful.",
    "Happy hacking!",
    "Don't panic. — The Hitchhiker's Guide to Reverse Engineering",
    "So long, and thanks for all the bytes.",
    "Time flies like an arrow; fruit flies like a banana. — also, CPUs fly like opcodes.",
    "I think, therefore I reverse.",
    "Cogito, ergo disassemblo.",
    "In the beginning was the Word, and the Word was 0x00.",
    "Let there be light. And there was LED.",
    "And on the seventh day, the programmer rested. JK, they pushed to prod on Friday.",
    "Friday deploy: living dangerously.",
    "Monday morning: git pull, git cry.",
    "Coffee: the programmer's fuel.",
    "Energy drinks: the hacker's rocket fuel.",
    "Sleep is for the weak (and the well-adjusted).",
    "One more bug... then I'll sleep.",
    "Just five more minutes of reversing...",
    "It's 3 AM. Perfect time to reverse a binary.",
    "The best code is written after midnight.",
    "The worst bugs are found after midnight.",
    "Rubber duck debugging: explaining code to a toy.",
    "The duck understands. The duck always understands.",
    "Stack overflow (the error, not the website).",
    "Heap overflow: when the stack isn't enough.",
    "BSS: Block Started by Symbol, ended by segfault.",
    "Global variables: shared state, shared nightmares.",
    "Thread safety: the programmer's unicorn.",
    "Mutex: mutual exclusion, mutual frustration.",
    "Semaphore: the traffic light of concurrency.",
    "Deadlock: when everyone waits forever.",
    "Livelock: when everyone is busy doing nothing.",
    "Starvation: when one thread hogs the buffet.",
    "Priority inversion: when the intern outranks the CTO.",
    "Context switching: the human and CPU equivalent of ADHD.",
    "Interrupt handler: the kernel's 911 operator.",
    "Watchdog timer: the system's last resort.",
    "Panic: kernel's way of saying 'I give up'.",
    "Oops: Linux kernel's gentle crash.",
    "BSOD: Windows' not-so-gentle crash.",
    "Kernel panic: not syncing — VFS: Unable to mount root.",
    "initramfs: the kernel's security blanket.",
    "systemd: love it or hate it, it init-iates everything.",
    "PID 1: the process that spawned them all.",
    "fork: because one process is never enough.",
    "exec: becoming someone else entirely.",
    "zombie process: dead but not gone.",
    "orphan process: alive but alone.",
    "daemon: the process that runs in the shadows.",
    "cron: time-based task scheduling, or 'did my job run?'.",
    "at: run once, forget forever.",
    "nohup: no hang up, keep going.",
    "Screen: the terminal multiplexer before tmux.",
    "tmux: terminal multiplexing for the modern age.",
    "SSH: Secure Shell, the remote worker's best friend.",
    "RSA key: the digital handshake.",
    "Certificate: the internet's ID card.",
    "Let's Encrypt: free HTTPS for everyone.",
    "HTTPS: because HTTP was too trusting.",
    "DNS: the internet's phone book.",
    "BGP: the internet's routing table of trust.",
    "TCP/IP: the protocol that runs the world.",
    "UDP: fire and forget.",
    "ICMP: ping pong for networks.",
    "ARP: the protocol that maps IPs to MACs.",
    "MAC address: the NIC's fingerprint.",
    "VLAN: virtual fences for networks.",
    "Subnet mask: the network's boundaries.",
    "NAT: the network's translator.",
    "Firewall: the network's bouncer.",
    "IDS: Intrusion Detection System, the network's alarm.",
    "IPS: Intrusion Prevention System, the network's bodyguard.",
    "WAF: Web Application Firewall, the website's shield.",
    "DPI: Deep Packet Inspection, reading your mail.",
    "VPN: the network's disguise.",
    "Tor: the network's anonymous mask.",
    "Proxy: the middleman.",
    "Load balancer: sharing is caring.",
    "CDN: Content Delivery Network, caching the world.",
    "Edge computing: processing at the frontier.",
    "IoT: Internet of Things, or Internet of Threats.",
    "Embedded: where software meets hardware.",
    "Firmware: the software that thinks it's hardware.",
    "JTAG: the hardware debugger's port.",
    "UART: the serial port that never dies.",
    "SPI: Serial Peripheral Interface, talking to chips.",
    "I2C: Inter-Integrated Circuit, the chip chat protocol.",
    "GPIO: General Purpose I/O, the maker's playground.",
    "Logic analyzer: seeing signals in time.",
    "Oscilloscope: the engineer's eye.",
    "Multimeter: the electrician's Swiss Army knife.",
    "Soldering iron: the hardware hacker's wand.",
    "PCB: Printed Circuit Board, the hardware's canvas.",
    "FPGA: Field Programmable Gate Array, hardware you can code.",
    "ASIC: Application Specific IC, hardware set in stone.",
    "Verilog: coding hardware.",
    "VHDL: Very Hard Description Language.",
    "RTL: Register Transfer Level, where hardware meets code.",
    "Synthesis: turning code into circuits.",
    "Place and route: Tetris for transistors.",
    "Timing closure: when nanoseconds matter.",
    "Clock domain crossing: the hardware's race condition.",
    "Metastability: Schrödinger's flip-flop.",
    "Setup and hold time: the flip-flop's personal space.",
    "Glitch: the hardware's transient tantrum.",
    "Power integrity: keeping the volts steady.",
    "Signal integrity: keeping the bits clean.",
    "EMI: Electromagnetic Interference, the invisible noise.",
    "ESD: Electrostatic Discharge, the silent killer.",
    "Thermal throttling: when the CPU gets too hot to handle.",
    "Overclocking: living on the edge.",
    "Undervolting: the efficiency hack.",
    "Heatsink: the CPU's personal AC.",
    "Liquid cooling: the enthusiast's flex.",
    "Fan curve: the audiophile's nemesis.",
    "Coil whine: the GPU's song.",
    "The sound of your CPU... is cheapbin.",
    /* ── More RE / hacker / chiptune culture quotes ────────────── */
    "That's not a bug, that's an undocumented feature.",
    "0xDEADC0DE: the zombie apocalypse of computing.",
    "IDA Pro: where binaries go to confess.",
    "objdump: the poor man's disassembler.",
    "PE format: Microsoft's gift to malware analysts.",
    "ELF: Executable and Linkable Format, not Santa's helper.",
    "Mach-O: Apple's binary format, twice the magic numbers.",
    "The shellcode doesn't care about your feelings.",
    "There's no place like 127.0.0.1.",
    "sudo make me a sandwich.",
    "It's not a vulnerability, it's a surprise backdoor.",
    "chmod 777: because security is overrated.",
    "rm -rf /: the fastest way to clean your disk.",
    "Wireshark: reading other people's packets since 2006.",
    "tcpdump: because packets have secrets.",
    "nmap: knocking on every port since 1997.",
    "Metasploit: point, click, own.",
    "CVE: Collect Vulnerabilities Everywhere.",
    "Zero-day: the hacker's holy grail.",
    "Patch Tuesday: Microsoft's monthly confession.",
    "Format string vulnerability: printf's revenge.",
    "Double free: memory's deja vu.",
    "ASLR: shuffle the deck, hope they can't find the card.",
    "DEP: Data Execution Prevention, the fun police.",
    "CFI: Control Flow Integrity, the bouncer at the club.",
    "KASLR: because attackers know where the kernel lives.",
    "Shadow stack: protecting return addresses since 2020.",
    "Fuzzing: throwing garbage at software until it breaks.",
    "AFL: American Fuzzy Lop, the fuzzer with the cutest name.",
    "Sanitizers: catching bugs before they catch you.",
    "Valgrind: memory errors are not optional.",
    "strace: follow the syscalls, find the truth.",
    "ltrace: library calls don't lie.",
    "ptrace: attach, peek, poke, repeat.",
    "DWARF: debugging information, not fantasy creatures.",
    "Symbol table: the binary's phone book.",
    "Stripped binary: the debugger's worst nightmare.",
    "GOT: Global Offset Table, not Game of Thrones.",
    "PLT: Procedure Linkage Table, one indirection to rule them all.",
    "Relocation: because absolute addresses are for quitters.",
    "Dynamic linking: sharing is caring.",
    "Static linking: because dependency hell is real.",
    "LD_PRELOAD: intercepting functions since forever.",
    "dlopen: loading libraries at runtime like a boss.",
    "Lazy binding: resolve it when you need it.",
    "TLS: Thread Local Storage, not the encryption one.",
    "BSS: Block Started by Symbol, or just 'zeroed stuff'.",
    "The .text section: where code goes to execute.",
    "The .data section: where initialized globals live.",
    "The .rodata section: strings and constants, read-only.",
    "The .bss section: zeroes, as far as the eye can see.",
    "The .plt section: trampolines for library calls.",
    "The .got section: indirection central.",
    "The .init section: code that runs before main.",
    "The .fini section: code that runs after main.",
    "The .comment section: compiler signatures and Easter eggs.",
    "The .note section: build IDs and vendor info.",
    "ELF magic: 7f 45 4c 46, the header that starts it all.",
    "MZ header: Mark Zbikowski's eternal signature.",
    "COFF: Common Object File Format, anything but common.",
    "a.out: the original binary format, prehistoric.",
    "LLVM bitcode: intermediate representation heaven.",
    "WebAssembly: the browser's assembly language.",
    "JIT compilation: compiling code while running code.",
    "Interpreter loop: fetch, decode, execute, repeat.",
    "Bytecode: not quite machine code, not quite source.",
    "Opcode table: the CPU's recipe book.",
    "Microcode: instructions inside instructions.",
    "CISC vs RISC: the eternal architecture debate.",
    "Superscalar: executing multiple instructions per clock.",
    "Out-of-order execution: the CPU's time machine.",
    "Branch prediction: guessing the future since 1995.",
    "Speculative execution: doing work you might throw away.",
    "Spectre: when speculation becomes a vulnerability.",
    "Meltdown: when the CPU's boundaries dissolve.",
    "Cache timing: the side channel that keeps on giving.",
    "Rowhammer: flipping bits by reading neighbors.",
    "Cold boot attack: when RAM remembers too much.",
    "Glitching: fault injection for fun and profit.",
    "Power analysis: the CPU's heartbeat reveals secrets.",
    "Differential power analysis: statistics meets hardware.",
    "JTAG: the hardware debugger's best friend.",
    "SWD: Serial Wire Debug, JTAG's simpler cousin.",
    "UART: the universal serial confessional.",
    "SPI flash: firmware lives here.",
    "I2C: two wires, infinite possibilities.",
    "Bus pirate: the hardware hacker's Swiss Army knife.",
    "Logic analyzer: seeing the ones and zeros in real time.",
    "Oscilloscope: because sometimes you need to see the wave.",
    "Saleae: the logic analyzer that doesn't suck.",
    "Firmware dump: extracting the software from the hardware.",
    "Binwalk: finding files inside files inside files.",
    "Entropy analysis: high entropy means encryption or compression.",
    "String extraction: the laziest form of reverse engineering.",
    "Cross-reference: where does this function get called?",
    "Call graph: visualizing the function hierarchy.",
    "Control flow graph: blocks and edges, the RE's map.",
    "Data flow analysis: tracking values through the code.",
    "Taint analysis: following the untrusted data.",
    "Symbolic execution: exploring all paths simultaneously.",
    "Angr: binary analysis framework, not an emotion.",
    "Z3: the SMT solver that powers everything.",
    "Ghidra's decompiler: from assembly to almost-C.",
    "Hex-Rays: the gold standard of decompilation.",
    "Radare2: the terminal-native reversing framework.",
    "Cutter: radare2 with a GUI, for the faint of heart.",
    "Binary Ninja: the reversing tool with the best API.",
    "Hopper: macOS reversing made visual.",
    "Class-dump: Objective-C reverse engineering 101.",
    "Frida: dynamic instrumentation for everything.",
    "Pin: Intel's dynamic binary instrumentation tool.",
    "DynamoRIO: dynamic binary analysis at scale.",
    "QEMU: emulate anything, anywhere.",
    "Unicorn: CPU emulation without the OS.",
    "Capstone: the disassembly framework that everyone uses.",
    "Keystone: the assembler framework, Capstone's sibling.",
    "LIEF: parsing binaries in Python, simply.",
    "pefile: Python's PE parser, tried and true.",
    "pyelftools: ELF parsing, the Python way.",
    "Construct: binary parsing with declarative syntax.",
    "Kaitai Struct: describe the format, generate the parser.",
    "Protocol buffers: serialization for the lazy.",
    "MessagePack: like JSON, but binary and fast.",
    "CBOR: Concise Binary Object Representation.",
    "ASN.1: the serialization format that predates the web.",
    "XOR encryption: the rotary phone of cryptography.",
    "ROT13: encryption that a child could break.",
    "Caesar cipher: because Julius needed secrets too.",
    "RC4: the stream cipher that refused to die.",
    "AES-NI: hardware-accelerated encryption.",
    "SHA-256: hashing with confidence.",
    "MD5: the hash that's been broken since 2004.",
    "CRC32: not encryption, despite what some think.",
    "HMAC: because hashes alone aren't enough.",
    "Key derivation: turning passwords into keys.",
    "Salt: making rainbow tables useless since 2001.",
    "Rainbow table: precomputed hashes for the impatient.",
    "Hashcat: cracking passwords at GPU speed.",
    "John the Ripper: the OG password cracker.",
    "Brute force: when all else fails, try everything.",
    "Dictionary attack: because people pick bad passwords.",
    "Side channel: when the implementation leaks secrets.",
    "Timing attack: measuring time reveals information.",
    "Replay attack: because once wasn't enough.",
    "Man-in-the-middle: the classic interception.",
    "DNS poisoning: hijacking the internet's phone book.",
    "ARP spoofing: because LAN security is an illusion.",
    "SQL injection: the vulnerability that won't die.",
    "Command injection: semicolons are dangerous.",
    "Path traversal: ../../../etc/passwd",
    "Deserialization: untrusted data, trusted execution.",
    "Prototype pollution: JavaScript's inheritance problem.",
    "SSRF: Server-Side Request Forgery, the internal network scanner.",
    "XXE: XML External Entity, when parsers read too much.",
    "CSRF: making browsers do your bidding.",
    "XSS: injecting scripts since 1999.",
    "CORS: Cross-Origin Resource Sharing, misconfigured.",
    "JWT: JSON Web Tokens, often implemented wrong.",
    "OAuth: delegation of authority, often misunderstood.",
    "SAML: XML-based authentication, XML-sized problems.",
    "Kerberos: three-headed dog guarding the network.",
    "LDAP: the directory nobody enjoys querying.",
    "Active Directory: the corporate hacker's playground.",
    "WMI: Windows Management Instrumentation, admin or attacker?",
    "PowerShell: the sysadmin's tool, the attacker's weapon.",
    "Living off the land: using built-in tools maliciously.",
    "LOLBins: legitimate tools, illegitimate uses.",
    "Certutil: downloading files the Microsoft way.",
    "WMIC: Windows Management from the command line.",
    "Mimikatz: extracting credentials since 2011.",
    "Pass-the-hash: why crack when you can reuse?",
    "Golden ticket: Kerberos authentication forever.",
    "DCSync: replicating domain controller secrets.",
    "BloodHound: mapping Active Directory attack paths.",
    "Cobalt Strike: the red team's Swiss Army knife.",
    "Beacon: phoning home to the C2 server.",
    "Implant: persistent access, subtle presence.",
    "Rootkit: hiding in plain sight.",
    "Bootkit: infecting the boot process.",
    "Hypervisor rootkit: beneath the operating system.",
    "Process hollowing: wearing another process's skin.",
    "DLL injection: loading code into another process.",
    "Thread hijacking: borrowing someone else's thread.",
    "Import Address Table hooking: redirecting API calls.",
    "Inline hooking: patching functions at runtime.",
    "ETW: Event Tracing for Windows, the telemetry backbone.",
    "Sysmon: logging everything the attacker does.",
    "YARA: pattern matching for malware hunters.",
    "Sigma: detection rules for log analysis.",
    "Snort: the original network IDS.",
    "Suricata: Snort's faster cousin.",
    "Zeek: network monitoring with a PhD.",
    "PCAP: Packet Capture, the network's flight recorder.",
    "Memory forensics: because RAM has secrets.",
    "Volatility: extracting truth from memory dumps.",
    "Rekall: another memory forensics framework.",
    "Disk forensics: recovering deleted evidence.",
    "Autopsy: the digital forensics GUI.",
    "Sleuth Kit: command-line forensics.",
    "dd: disk duplication, evidence preservation.",
    "Hashing evidence: proving nothing was altered.",
    "Chain of custody: keeping evidence admissible.",
    "Timeline analysis: reconstructing the attack.",
    "Artifact: evidence left behind by attacker activity.",
    "IOC: Indicator of Compromise, breadcrumbs of evil.",
    "TTPs: Tactics, Techniques, and Procedures.",
    "MITRE ATT&CK: the framework that maps attacks.",
    "Kill chain: the steps of a cyber attack.",
    "Diamond model: adversary, capability, infrastructure, victim.",
    "Threat intelligence: knowing your enemy.",
    "APT: Advanced Persistent Threat, the nation-state kind.",
    "Red team: thinking like the attacker.",
    "Blue team: defending the castle.",
    "Purple team: because collaboration beats competition.",
    "Bug bounty: getting paid to break stuff.",
    "Responsible disclosure: telling the vendor first.",
    "Full disclosure: telling everyone at once.",
    "CTF: Capture The Flag, competitive hacking.",
    "PWN: exploiting a binary challenge.",
    "RE challenge: figure out what this program does.",
    "Web challenge: find the flag in the website.",
    "Crypto challenge: break the cipher, get the flag.",
    "Forensics challenge: extract the hidden data.",
    "OSINT challenge: find it on the internet.",
    "Stego challenge: hidden messages in images.",
    "8-bit music: the sound of nostalgia.",
    "Chiptune: music made by hardware, not musicians.",
    "SID chip: the Commodore 64's voice.",
    "AY-3-8910: the ZX Spectrum's sound chip.",
    "Yamaha YM2612: the Sega Genesis sound.",
    "Ricoh 2A03: the NES's beating heart.",
    "Game Boy's wave channel: 4-bit audio bliss.",
    "MOD tracker: where chiptune meets sampling.",
    "Amiga Paula: four channels of pure joy.",
    "VRC6: extra sound channels for the Famicom.",
    "Sunsoft bass: the deepest NES sound ever made.",
    "Duty cycle: the shape of the square wave.",
    "Triangle wave: the NES bass sound.",
    "Noise channel: the drummer of the chip.",
    "DPCM: Delta Pulse Code Modulation, NES samples.",
    "Arpeggio: fake chords on a chip.",
    "Vibrato: wobbling the pitch for expression.",
    "Portamento: sliding between notes smoothly.",
    "Envelope: shaping sound over time.",
    "ADSR: Attack, Decay, Sustain, Release.",
    "LFO: Low Frequency Oscillator, the modulator.",
    "PWM: Pulse Width Modulation, the timbre knob.",
    "Detune: slightly off-pitch for thickness.",
    "Echo: delay line, the cheapest reverb.",
    "Ring modulation: multiplying waveforms for metallic tones.",
    "FM synthesis: frequency modulation magic.",
    "Wavetable: cycling through tiny sample tables.",
    "Chip music lives in the space between code and art.",
    "Every byte has a melody waiting to be heard.",
    "The best debugger is a good night's sleep.",
    "Code is poetry... written in hexadecimal.",
    "Real hackers use butterflies.",
    "DEADBEEF CAFEBABE FEEDFACE 8BADF00D.",
    "In the beginning was the command line.",
    "We do these things not because they are easy...",
    "The Matrix has you... running nm on its binary.",
    "May the --force be with you.",
    "I see dead processes.",
    "To infinity and beyond the buffer boundary.",
    "One does not simply walk into a stripped binary.",
    "My other car is a kernel module.",
    "Segfault: the CPU's way of saying 'no'.",
    "Core dump: the program's dying confession.",
    "Panic: when even the kernel gives up.",
    "Oops: the kernel's embarrassed cough.",
    "BUG(): the developer's assertion of impossibility.",
    "WARN_ON(): the kernel's raised eyebrow.",
    "printk: debugging the kernel since 1991.",
    "dmesg: the kernel's diary.",
    "syslog: where Unix stores its secrets.",
    "journalctl: systemd's version of reading logs.",
    "Magic SysRq: the keyboard shortcut that saves systems.",
    "Kernel module: extending the kernel, at your own risk.",
    "eBPF: programmable kernel without the reboot.",
    "Seccomp: sandboxing at the syscall level.",
    "Capabilities: fine-grained privilege control.",
    "Namespaces: the building blocks of containers.",
    "Cgroups: resource limits for processes.",
    "Every binary tells a story.",
    "Reverse engineering: reading the story backwards.",
    "Malware analysis: reading a horror story backwards.",
    "Firmware reversing: reading the hardware's story.",
    "Protocol reversing: decoding the conversation.",
    "Game hacking: rewriting the rules.",
    "Cheat engine: finding values in memory.",
    "Speed hack: because waiting is boring.",
    "Wallhack: seeing through virtual walls.",
    "Aimbot: when your skills need an upgrade.",
    "Anti-cheat: the arms race continues.",
    "Code signing: proving who wrote the code.",
    "Certificate pinning: trusting specific certificates.",
    "SSL stripping: downgrading security for profit.",
    "TLS interception: reading encrypted traffic.",
    "Man-in-the-browser: the inside job.",
    "Keylogger: recording every keystroke.",
    "Screen scraper: watching everything you see.",
    "Clipboard hijacker: stealing what you copy.",
    "Ransomware: your files, encrypted, pay up.",
    "Cryptominer: your CPU, their profit.",
    "Botnet: an army of compromised machines.",
    "DDoS: overwhelming the target with traffic.",
    "Worm: malware that spreads itself.",
    "Trojan: malware in disguise.",
    "Dropper: delivering the payload.",
    "Packer: compressing and obfuscating malware.",
    "Crypter: encrypting malware to avoid detection.",
    "Metamorphic: malware that rewrites itself.",
    "Polymorphic: malware that changes appearance.",
    "Sandbox evasion: detecting the analysis environment.",
    "VM detection: checking for virtual machines.",
    "Anti-debug: making debuggers useless.",
    "Opaque predicates: obfuscation through confusion.",
    "Control flow flattening: making code unreadable.",
    "Dead code insertion: noise in the signal.",
    "String encryption: hiding the evidence.",
    "API hashing: resolving functions by hash.",
    "Syscall: talking directly to the kernel.",
    "VDSO: virtual dynamic shared object, fast syscalls.",
    "Vsyscall: the original fast syscall mechanism.",
    "SYSRET: returning from kernel to user mode.",
    "MSR: Model Specific Registers, the CPU's config.",
    "CPUID: asking the CPU about itself.",
    "RDTSC: reading the timestamp counter.",
    "Cheapbin: where every binary finds its voice.",
};


#define NUM_RE_QUOTES (sizeof(RE_QUOTES) / sizeof(RE_QUOTES[0]))

/* ── x86/ARM Opcodes for display ───────────────────────────────────── */

static const char *OPCODES[] = {
    "NOP", "MOV", "PUSH", "POP", "CALL", "RET", "JMP", "JNZ", "JZ", "JE",
    "JNE", "JG", "JL", "JGE", "JLE", "JA", "JB", "JAE", "JBE", "CMP",
    "TEST", "AND", "OR", "XOR", "NOT", "NEG", "SHL", "SHR", "SAR", "SAL",
    "ROL", "ROR", "RCL", "RCR", "ADD", "SUB", "MUL", "IMUL", "DIV", "IDIV",
    "INC", "DEC", "LEA", "XCHG", "INT", "SYSCALL", "SYSENTER", "LEAVE",
    "ENTER", "HLT", "CPUID", "RDTSC", "LOOP", "LOOPZ", "LOOPNZ",
    "REP", "REPZ", "REPNZ", "MOVS", "CMPS", "SCAS", "LODS", "STOS",
    "IN", "OUT", "CLI", "STI", "CLC", "STC", "CLD", "STD", "CBW", "CWD",
    "CDQ", "CWDE", "CDQE", "BSWAP", "BSF", "BSR", "BT", "BTC", "BTR",
    "BTS", "CMC", "LAHF", "SAHF", "PUSHF", "POPF",
    "MOVZX", "MOVSX", "CMOVZ", "CMOVNZ", "CMOVG", "CMOVL",
    "SETNE", "SETE", "SETG", "SETL", "SETGE", "SETLE",
    "ENDBR64", "ENDBR32", "LFENCE", "SFENCE", "MFENCE",
    "PAUSE", "PREFETCH", "CLFLUSH",
    /* SSE/AVX */
    "MOVAPS", "MOVUPS", "ADDPS", "MULPS", "SUBPS", "DIVPS",
    "PXOR", "PUNPCKLBW", "PSHUFD", "SHUFPS",
    "VMOVDQA", "VADDPS", "VMULPS", "VPXOR",
    /* ARM */
    "LDR", "STR", "LDP", "STP", "BL", "BLR", "BR", "B.EQ", "B.NE",
    "B.GT", "B.LT", "B.GE", "B.LE", "CBZ", "CBNZ", "TBZ", "TBNZ",
    "ADRP", "MADD", "MSUB", "UDIV", "SDIV", "LSL", "LSR", "ASR",
    "AND", "ORR", "EOR", "MVN", "REV", "CLZ", "RBIT",
    "SVC", "HVC", "SMC", "MRS", "MSR", "DMB", "DSB", "ISB",
    "WFI", "WFE", "SEV", "YIELD", "ERET",
};

#define NUM_OPCODES (sizeof(OPCODES) / sizeof(OPCODES[0]))

/* ── Register names ────────────────────────────────────────────────── */

static const char *REGISTERS[] = {
    /* x86-64 */
    "RAX", "RBX", "RCX", "RDX", "RSI", "RDI", "RBP", "RSP",
    "R8", "R9", "R10", "R11", "R12", "R13", "R14", "R15",
    "EAX", "EBX", "ECX", "EDX", "ESI", "EDI", "EBP", "ESP",
    "AX", "BX", "CX", "DX", "AL", "BL", "CL", "DL",
    "AH", "BH", "CH", "DH", "RIP", "EFLAGS", "CS", "DS",
    "ES", "FS", "GS", "SS", "CR0", "CR3", "CR4", "DR0",
    "DR7", "XMM0", "XMM1", "XMM7", "YMM0", "ZMM0",
    /* ARM64 */
    "X0", "X1", "X2", "X3", "X8", "X16", "X29", "X30",
    "SP", "PC", "LR", "CPSR", "NZCV", "FPCR",
    "W0", "W1", "W2", "W3",
    "V0", "V1", "D0", "D1", "S0", "S1", "Q0", "Q1",
};

#define NUM_REGISTERS (sizeof(REGISTERS) / sizeof(REGISTERS[0]))

/* ── Section names ─────────────────────────────────────────────────── */

static const char *SECTION_NAMES[] = {
    ".text", ".data", ".bss", ".rodata", ".plt", ".got",
    ".got.plt", ".init", ".fini", ".ctors", ".dtors",
    ".dynamic", ".dynsym", ".dynstr", ".symtab", ".strtab",
    ".shstrtab", ".rel.plt", ".rel.dyn", ".note", ".comment",
    ".debug_info", ".debug_line", ".debug_str", ".eh_frame",
    "__TEXT", "__DATA", "__LINKEDIT", "__OBJC",
    "__cstring", "__stub_helper", "__la_symbol_ptr",
};

#define NUM_SECTION_NAMES (sizeof(SECTION_NAMES) / sizeof(SECTION_NAMES[0]))

/* ── Fake disassembly snippets ─────────────────────────────────────── */

static const char *FAKE_DISASM[] = {
    "push   rbp",
    "mov    rbp, rsp",
    "sub    rsp, 0x20",
    "mov    [rbp-8], rdi",
    "lea    rax, [rip+0x42]",
    "call   0xdeadbeef",
    "test   eax, eax",
    "jnz    0x401337",
    "xor    eax, eax",
    "pop    rbp",
    "ret",
    "nop",
    "mov    edi, 0x1",
    "mov    rsi, rsp",
    "mov    edx, 0xff",
    "syscall",
    "cmp    byte [rdi], 0",
    "je     .done",
    "movzx  ecx, byte [rsi]",
    "xor    cl, al",
    "mov    [rdi], cl",
    "inc    rdi",
    "jmp    .loop",
    "push   r12",
    "push   r13",
    "mov    r12, rdi",
    "mov    r13, rsi",
    "call   malloc",
    "test   rax, rax",
    "jz     .error",
    "mov    [r12], rax",
    "pop    r13",
    "pop    r12",
    "endbr64",
    "bnd jmp qword [rip]",
    "lea    rdi, [rel msg]",
    "call   puts@plt",
    "mov    eax, 0x3c",
    "xor    edi, edi",
    "int    0x80",
    "svc    #0x80",
    "bl     _printf",
    "ldr    x0, [sp, #0x10]",
    "str    x1, [x0, #8]",
    "cbz    w0, .Lbb1",
    "adrp   x8, _main@PAGE",
    "add    x8, x8, _main@PAGEOFF",
    "blr    x8",
    "ldp    x29, x30, [sp], #0x10",
};

#define NUM_FAKE_DISASM (sizeof(FAKE_DISASM) / sizeof(FAKE_DISASM[0]))

#endif /* CHEAPBIN_RE_DATA_H */
